name: Read Hello.txt

on:
  push:
    branches:
      - master

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read and Output File Content
        run: cat hello.txt
